
version: "3"

networks:
  public: {}
  
services:
  prod:
    container_name: prod
    image: same-same-but-diffy:prod
    ports:
      - "8080:80"
    networks:
      - public
  
  dev:
    container_name: dev
    image: same-same-but-diffy:dev
    ports:
      - "8181:80"
    networks:
      - public
  
  goreplay:
    container_name: gor
    build:
      context: ./
      dockerfile: Dockerfile
    image: goreplay
    network_mode: "host"
    command:
      - '--input-raw=:8080'
      - '--output-http=http://127.0.0.1:8181'
      - '--input-raw-track-response'
      - '--output-http-track-response'
      #- '--middleware=sh /opt/compare.sh'
      - '--output-http-compatibility-mode'